export const exercises: string[] = [
    'Type Ahead', 
    'Array Cardio Day 2',
    'Fun with HTML5 Canvas',
    'Dev Tools Domination',
    'Hold Shift and Check Checkboxes',
    'Custom Video Player',
    'Key Sequence Detection',
    'Slide in on Scroll',
    'Javascript References VS Copying',
    'LocalStorage',
    'Mouse Move Shadow',
    'Sort Without Articles',
    'Adding Up times with Reduce',
    'Webacam Fun',
    'Speech Detection',
    'Geolocation',
    'Follow Along Link Highlighter',
    'Speech Synthesis',
    'Sticky Nav',
    'Event Capture, Propagation, Bubbling and Once',
    'Stripe Follow Along Nav',
    'Click and Drag',
    'Countdown Timer',
    'Whack A Mole'
]