import { Content } from './content';

export const MOCKCONTENT: Content[] = [
    { name: "JavaScript Drum Kit", routerLink: ['drumkit'] },
    { name: "JS and CSS Clock", routerLink: ['clock'] },
    { name: "CSS Variables", routerLink: ['cssVariables'] },
    { name: "Array Cardio Day 1", routerLink: ['arrayCardioOne'] },
    { name: "Flex Panel Gallery", routerLink: ['flexPanelGallery'] },
    { name: "Type Ahead", routerLink: ['typeHead'] },
    { name: "Array Cardio Day 2", routerLink: ['arrayCardioTwo'] },
    { name: "Fun with HTML 5 Canvas", routerLink: ['funCanvas'] },
    { name: "Dev Tools Domination", routerLink: ['devTools'] },
    { name: "Hold Shift and Check Checkboxes", routerLink: ['holdShiftClickCheckboxes'] },
    { name: "Custom Video Player", routerLink: ['videoPlayer'] },
    { name: "Key Sequence Detection", routerLink: ['keySequenceDetection'] },
    { name: "Slide in on Scroll", routerLink: ['slideScroll'] },
    { name: "JavaScript References VS Copying", routerLink: ['refVsCopying'] },
    { name: "LocalStorage", routerLink: ['localStorage'] },
    { name: "Mouse Move Shadow", routerLink: ['mouseMoveShadow'] },
    { name: "Sort Without Articles", routerLink: ['sort'] },
    { name: "Adding Up Times with Reduce", routerLink: ['addWithReduce'] },
    { name: "Webcam Fun", routerLink: ['webcamFun'] },
    { name: "Speech Detection", routerLink: ['speechDetection'] },
    { name: "Geolocation", routerLink: ['geolocation'] },
    { name: "Follow Along Link Highlighter", routerLink: ['highlighter'] },
    { name: "Speech Synthesis", routerLink: ['speechSynthesis'] },
    { name: "Sticky Nav", routerLink: ['stickyNav'] },
    { name: "Event Capture, Propagation, Bubbling and Once", routerLink: ['events'] },
    { name: "Strike Follow Along Nav", routerLink: ['strikeFollowAlongNav'] },
    { name: "Click and Drag", routerLink: ['clickAndDrag'] },
    { name: "Video Speed Controller", routerLink: ['video'] },
    { name: "Countdown Timer", routerLink: ['countdownTimer'] },
    { name: "Whack A Mole", routerLink: ['whackAMole'] }
]